apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-spring
  namespace: todo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-spring
  template:
    metadata:
      labels:
        app: postgres-spring
    spec:
      volumes:
      - name: postgres-spring-storage
        persistentVolumeClaim:
          claimName: postgres-spring-pvc
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-12:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-spring-credentials
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-spring-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-spring-credentials
              key: POSTGRES_DB
        - name: POSTGRESQL_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-spring-credentials
              key: POSTGRES_PORT
        volumeMounts:
        - name: postgres-spring-storage
          mountPath: /var/lib/pgsql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-spring-pvc
  namespace: todo-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-spring-service
  namespace: todo-demo
spec:
  selector:
    app: postgres-spring
  ports:
  - name: postgres-spring
    port: 5432
    targetPort: 5432
  type: ClusterIP

